# Site settings
title: Journey to Code
header-img: img/home-bg.png
email: svern99@aol.com
copyright_name: sandyvern
description: > # this means to ignore newlines until "baseurl:"
  My journey to a new career path to become a web developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: SandyVern
github_username:  sandyvern
learn_profile: sandyvern
email_username: svern99@aol.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
